// Generated by Apple Swift version 6.3.3 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef MWDATINPUTS_SWIFT_H
#define MWDATINPUTS_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MWDATInputs",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import MWDATCore;
@import ObjectiveC;
#elif defined(__OBJC__)
#import <MWDATCore/MWDATCore-Swift.h>
#import <objc/objc-exception.h>
#import <objc/NSObjCRuntime.h>
#import <objc/objc-sync.h>
#import <objc/message.h>
#import <objc/objc.h>
#import <objc/runtime.h>
#import <objc/NSObject.h>
#import <objc/objc-auto.h>
#import <objc/objc-api.h>
#else
#include <MWDATCore/MWDATCore-Swift.h>
#include <objc/objc-exception.h>
#include <objc/NSObjCRuntime.h>
#include <objc/objc-sync.h>
#include <objc/message.h>
#include <objc/objc.h>
#include <objc/runtime.h>
#include <objc/NSObject.h>
#include <objc/objc-auto.h>
#include <objc/objc-api.h>
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MWDATInputs",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// A named hardware button.
/// @Unpublishable
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATButtonType, "ObjC_ButtonType", closed) {
/// The primary action button.
  MWDATButtonTypeAction = 0,
/// Not a button event — set when the enclosing <code>MWDATInputEvent/type</code> is not <code>button</code>.
  MWDATButtonTypeUnknown = 1,
};

/// The kind of capture interaction.
/// @Unpublishable
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATCapturePressType, "ObjC_CapturePressType", closed) {
/// A single short press of the capture button. Defaults to capturing a photo.
  MWDATCapturePressTypeShortPress = 0,
/// A press and hold of the capture button. Defaults to starting a video recording.
  MWDATCapturePressTypeHold = 1,
/// A double press of the capture button. Defaults to stopping an in-progress video recording.
  MWDATCapturePressTypeDoublePress = 2,
/// Not a capture event — set when the enclosing <code>MWDATInputEvent/type</code> is not <code>capture</code>.
  MWDATCapturePressTypeUnknown = 3,
};

@class MWDATInputsConfiguration;
@class NSError;
@class MWDATInputs;
@interface MWDATDeviceSession (SWIFT_EXTENSION(MWDATInputs))
/// Creates and registers an inputs capability on this device session.
/// The session must be in <code>MWDATDeviceSessionStateStarted</code> state. If it is not, this returns
/// <code>nil</code> and populates <code>error</code> with <code>DeviceSessionError/sessionIdle</code>. Any other failure is
/// thrown by the underlying capability and surfaced through <code>error</code>.
/// @Unpublishable
- (MWDATInputs * _Nullable)addInputsWithConfiguration:(MWDATInputsConfiguration * _Nonnull)configuration error:(NSError * _Nullable * _Nullable)outError SWIFT_WARN_UNUSED_RESULT;
/// Removes the inputs capability from this session and stops it.
/// Returns <code>true</code> on success, or <code>false</code> and populates <code>error</code> if the session is not started
/// or has no inputs capability.
/// @Unpublishable
- (BOOL)removeInputsAndReturnError:(NSError * _Nullable * _Nullable)outError SWIFT_WARN_UNUSED_RESULT;
@end

/// The phase of a drag interaction.
/// @Unpublishable
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATDragAction, "ObjC_DragAction", closed) {
/// The pointer went down, beginning the drag.
  MWDATDragActionDown = 0,
/// The pointer moved while down.
  MWDATDragActionMove = 1,
/// The pointer went up, ending the drag.
  MWDATDragActionUp = 2,
/// Not a drag event — set when the enclosing <code>MWDATInputEvent/type</code> is not <code>drag</code>.
  MWDATDragActionUnknown = 3,
};

SWIFT_ENUM_FWD_DECL(NSInteger, MWDATInputEventType)
SWIFT_ENUM_FWD_DECL(NSInteger, MWDATInputSource)
SWIFT_ENUM_FWD_DECL(NSInteger, MWDATNavDirection)
/// Objective-C compatible input event.
/// Inspect <code>type</code> to decide which fields are meaningful. Fields not relevant to the current
/// <code>type</code> carry default values.
/// @Unpublishable
SWIFT_CLASS_NAMED("ObjC_InputEvent")
@interface MWDATInputEvent : NSObject
/// The kind of interaction this event represents.
@property (nonatomic, readonly) enum MWDATInputEventType type;
/// The surface that produced this event.
@property (nonatomic, readonly) enum MWDATInputSource source;
/// The event time of this input event, in milliseconds.
@property (nonatomic, readonly) int64_t timestampMs;
/// The navigation direction, when <code>type</code> is <code>MWDATInputEventType/nav</code>.
@property (nonatomic, readonly) enum MWDATNavDirection navDirection;
/// The button, when <code>type</code> is <code>MWDATInputEventType/button</code>.
@property (nonatomic, readonly) enum MWDATButtonType button;
/// The capture press type, when <code>type</code> is <code>MWDATInputEventType/capture</code>.
@property (nonatomic, readonly) enum MWDATCapturePressType capturePressType;
/// The drag phase, when <code>type</code> is <code>MWDATInputEventType/drag</code>.
@property (nonatomic, readonly) enum MWDATDragAction dragAction;
/// The absolute x coordinate, in the device’s input coordinate space, when <code>type</code> is
/// <code>MWDATInputEventType/drag</code>.
@property (nonatomic, readonly) float x;
/// The absolute y coordinate, in the device’s input coordinate space, when <code>type</code> is
/// <code>MWDATInputEventType/drag</code>.
@property (nonatomic, readonly) float y;
/// The relative x delta, in the same units, when <code>type</code> is <code>MWDATInputEventType/drag</code>.
@property (nonatomic, readonly) float dx;
/// The relative y delta, in the same units, when <code>type</code> is <code>MWDATInputEventType/drag</code>.
@property (nonatomic, readonly) float dy;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// The kind of an <code>ObjC_InputEvent</code>.
/// @Unpublishable
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATInputEventType, "ObjC_InputEventType", closed) {
/// A directional navigation gesture.
  MWDATInputEventTypeNav = 0,
/// A selection / confirm interaction.
  MWDATInputEventTypeSelect = 1,
/// A back / dismiss interaction.
  MWDATInputEventTypeBack = 2,
/// A named hardware button press.
  MWDATInputEventTypeButton = 3,
/// A capture button interaction (photo or video).
  MWDATInputEventTypeCapture = 4,
/// A drag interaction, reporting absolute and relative pointer coordinates.
  MWDATInputEventTypeDrag = 5,
};

/// The device surface that produced an input event.
/// @Unpublishable
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATInputSource, "ObjC_InputSource", closed) {
/// The capacitive touchpad on the glasses.
  MWDATInputSourceCaptouch = 0,
/// Neural Band discrete gesture input.
  MWDATInputSourceNeuralBand = 1,
/// The dedicated capture button on the glasses.
  MWDATInputSourceCaptureButton = 2,
/// The dedicated action button on the glasses.
  MWDATInputSourceActionButton = 3,
/// Neural Band pinch-and-drag input.
  MWDATInputSourceNeuralBandDrag = 4,
/// The source could not be determined.
  MWDATInputSourceUnknown = 5,
};

SWIFT_ENUM_FWD_DECL(NSInteger, MWDATInputsState)
SWIFT_ENUM_FWD_DECL(NSInteger, MWDATInputsError)
@class MWDATInputsListenerToken;
/// Objective-C bridge for receiving input events from a connected wearable.
/// @Unpublishable
SWIFT_CLASS_NAMED("ObjC_Inputs")
@interface MWDATInputs : NSObject
/// The current state of this inputs capability.
@property (nonatomic, readonly) enum MWDATInputsState state;
/// Callback invoked when the inputs state changes.
@property (nonatomic, copy) void (^ _Nullable onStateChanged)(enum MWDATInputsState);
/// Callback invoked for each input event.
@property (nonatomic, copy) void (^ _Nullable onEvent)(MWDATInputEvent * _Nonnull);
/// Callback invoked when the Inputs capability emits an error.
@property (nonatomic, copy) void (^ _Nullable onError)(enum MWDATInputsError);
/// Adds a listener for inputs state changes.
- (MWDATInputsListenerToken * _Nonnull)addStateListener:(void (^ _Nonnull)(enum MWDATInputsState))listener SWIFT_WARN_UNUSED_RESULT;
/// Adds a listener for inputs errors.
- (MWDATInputsListenerToken * _Nonnull)addErrorListener:(void (^ _Nonnull)(enum MWDATInputsError))listener SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSNumber;
/// Objective-C compatible inputs capability configuration.
/// @Unpublishable
SWIFT_CLASS_NAMED("ObjC_InputsConfiguration")
@interface MWDATInputsConfiguration : NSObject
/// The input sources to capture, as <code>ObjC_InputSource</code> raw values boxed in <code>NSNumber</code>. An empty
/// array means all available sources. (An array of enum values is not representable in
/// Objective-C, so raw values are used.)
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull sources;
/// When <code>true</code>, Back interactions on the glasses are delivered to your app as input events
/// instead of being handled by the system. When <code>false</code>, the system handles Back and your app
/// does not receive it. Defaults to <code>true</code>.
@property (nonatomic, readonly) BOOL consumeBack;
/// Creates a configuration.
/// \param sources The input sources to capture, as <code>ObjC_InputSource</code> raw values boxed in
/// <code>NSNumber</code>. Pass an empty array to capture all available sources.
///
/// \param consumeBack When <code>true</code>, Back interactions on the glasses are delivered to your app as
/// input events instead of being handled by the system. When <code>false</code>, the system handles
/// Back.
///
- (nonnull instancetype)initWithSources:(NSArray<NSNumber *> * _Nonnull)sources consumeBack:(BOOL)consumeBack OBJC_DESIGNATED_INITIALIZER;
/// Creates a configuration that captures all available input sources and delivers Back
/// interactions to your app.
- (nonnull instancetype)init;
@end

/// Errors that can occur while an <code>Inputs</code> capability is active.
/// @Unpublishable
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATInputsError, "ObjC_InputsError", open) {
/// The app has not been granted permission to receive input events.
  MWDATInputsErrorPermissionDenied = 0,
/// The communication channel to the device closed unexpectedly.
  MWDATInputsErrorConnectionClosed = 1,
/// The capability did not become active before the activation deadline elapsed.
  MWDATInputsErrorActivationTimeout = 2,
/// The device disconnected while the capability was active.
  MWDATInputsErrorDeviceDisconnected = 3,
/// The communication channel reported a failure.
  MWDATInputsErrorCommunicationError = 4,
/// The device refused to activate the capability, or activation could not be attempted (for
/// example the input capability is unsupported or the communication channel was unavailable).
/// Unlike <code>activationTimeout</code>, this is a definitive failure rather than an elapsed deadline.
  MWDATInputsErrorActivationFailed = 5,
/// Inputs are unavailable on the connected device.
  MWDATInputsErrorCapabilityUnavailable = 6,
};

/// A token that can be used to cancel an inputs listener subscription.
/// @Unpublishable
SWIFT_CLASS_NAMED("ObjC_InputsListenerToken")
@interface MWDATInputsListenerToken : NSObject
/// Requests cancellation of the listener subscription.
/// important:
/// Cancellation completes asynchronously. This method returns immediately and does
/// not wait for teardown, so listener callbacks already scheduled or in flight may still be
/// delivered after it returns. There is no completion signal; do not assume “no more callbacks”
/// the instant this returns.
- (void)cancel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// The lifecycle state of an inputs capability.
/// @Unpublishable
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATInputsState, "ObjC_InputsState", closed) {
/// Created but not yet activated, cleanly removed, or ended by an error.
  MWDATInputsStateInactive = 0,
/// Waiting for the device to activate the capability.
  MWDATInputsStateActivating = 1,
/// Active and delivering events.
  MWDATInputsStateActive = 2,
/// Winding down after clean removal.
  MWDATInputsStateDeactivating = 3,
};

/// A directional navigation gesture.
/// @Unpublishable
typedef SWIFT_ENUM_NAMED(NSInteger, MWDATNavDirection, "ObjC_NavDirection", closed) {
/// An upward navigation gesture.
  MWDATNavDirectionUp = 0,
/// A downward navigation gesture.
  MWDATNavDirectionDown = 1,
/// A leftward navigation gesture.
  MWDATNavDirectionLeft = 2,
/// A rightward navigation gesture.
  MWDATNavDirectionRight = 3,
/// Not a navigation event — set when the enclosing <code>MWDATInputEvent/type</code> is not <code>nav</code>.
  MWDATNavDirectionUnknown = 4,
};

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif
